### ISSUE TITLE
About the device 

### ISSUE THREAD

**Issue by revaeb** [googleinterns/wss#10]
Hi, thx for your work!
I am trying to reproduce your work on 2 gpu,
so I run the following comand:

python train_wss.py \
  --logtostderr \
  --train_split="8_clean" \
  --train_split_cls="train_aug" \
  --model_variant="xception_65" \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=16 \
  --decoder_output_stride=4 \
  --train_crop_size="513,513" \
  --num_clones=2 \
  --train_batch_size=8 \
  --training_number_of_steps="30000" \
  --fine_tune_batch_norm=true \
  --tf_initial_checkpoint="/wss-master/init/deeplabv3_xception_2018_01_04/model.ckpt" \
  --train_logdir="/wss-master/train_log" \
  --dataset_dir="/wss-master/data/pascal_voc_seg"

But it seems that the gpus are not utilized, the code just run on cpus, 
I'm not quite familiar with tensorflow, could you plz give me some hints to solve this problem?
Thx!

**Comment by Yuliang-Zou** [comment]
Did you install the correct version of tensorflow? Maybe you install the cpu-only version?

**Comment by revaeb** [comment]
> 

I'll check it right now!Thx!

**Comment by revaeb** [comment]
> Did you install the correct version of tensorflow? Maybe you install the cpu-only version?

It seems that I installed the tf gpu-version correctly, do you know any other reasons? Feel sorry to bother you:(
