### ISSUE TITLE
Concrete results on COCO

### ISSUE THREAD

**Issue by LiheYoung** [googleinterns/wss#13]
Hi,

Would you mind telling the concrete results of ``PseudoSeg`` and ``Supervised``  in Figure 3b of the COCO dataset? It will help me a lot, thanks.

**Comment by LiheYoung** [comment]
And are they based on DeepLabv3+ and Xception-65, instead of ResNet-50/101?

**Comment by Yuliang-Zou** [comment]
Hi @LiheYoung , the results are shown as follows:
supervised: 42.24, 37.8, 33.6, 27.96, 22.94
ours: 43.64, 41.75, 39.11, 37.11, 29.78
The results are based on DeepLabv3+ w/ Xception-65. Hope this helps.

**Comment by LiheYoung** [comment]
Wow, thanks very much!
