### ISSUE TITLE
More data splits information

### ISSUE THREAD

**Issue by charlesCXK** [googleinterns/wss#3]
Hi, thanks for sharing! I have two questions about the data splits:
1. Could you please supply `2_clean.txt` for PASCAL VOC?
2. Could you tell me which split of 1/16 data @VOC did you use in Table 2 in the main paper? Since you have supplied 3 different splits of 1/16 data in this repo, which makes me confused.

Thanks again!

**Comment by Yuliang-Zou** [comment]
Hi @charlesCXK , thanks for your interest.
1. I will upload that split soon.
2. We use the `16_clean_3.txt` in the main paper.

**Comment by Yuliang-Zou** [comment]
Hi @charlesCXK , you can find `2_clean.txt` [here](https://filebox.ece.vt.edu/~ylzou/summer2020pseudoseg/splits/2_clean.txt)

**Comment by charlesCXK** [comment]
Thank you very much!
